FROM tomcat:9.0-jdk8-temurin-focal
LABEL author=Rajanikanth
RUN curl https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war --output /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
